$(document).ready(function(){function t(){for(var t=$(".input--minoru"),e=0;e<t.length;e++)t.eq(e).find(".wpcf7-form-control-wrap").before(t.eq(e).find(".input__field--yoko"))}var e=(navigator.userAgent.toLowerCase().indexOf("chrome/")>-1,navigator.userAgent.toLowerCase().indexOf("firefox/")>-1,navigator.userAgent.toLowerCase().indexOf("safari/")>-1,navigator.userAgent.toLowerCase().indexOf("opera/")>-1,navigator.userAgent.toLowerCase().indexOf("msie")>-1,{Android:function(){return navigator.userAgent.match(/Android/i)},BlackBerry:function(){return navigator.userAgent.match(/BlackBerry/i)},iOS:function(){return navigator.userAgent.match(/iPhone|iPad|iPod/i)},Opera:function(){return navigator.userAgent.match(/Opera Mini/i)},Windows:function(){return navigator.userAgent.match(/IEMobile/i)},any:function(){return e.Android()||e.BlackBerry()||e.iOS()||e.Opera()||e.Windows()}});e.any(),$("#menu").on("click",function(){$("#menu-list").find("a").removeClass("mli-active2"),$("#menu-list").find(".menu-listsub").removeClass("menu-listsub-active"),$("#menu-list").toggleClass("menu-list-active"),$("#menu").toggleClass("menu-active")}),$("#menu-list").on("click","a",function(){$("#menu-list").find("a").removeClass("mli-active").addClass("mli-active2"),$("#menu-list").find(".menu-listsub").removeClass("menu-listsub-active"),$(".menu-listsub").find("a").removeClass(),$(this).addClass("mli-active"),$(this).siblings("#menu-list").find("a").removeClass(),$(this).siblings(".menu-listsub").addClass("menu-listsub-active")}),jQuery(window).width()>992&&
skrollr.init({  
forceHeight:!1,        
    mobileCheck: function() {
        //hack - forces mobile version to be off
        return false;
    }
});
var i=new WOW({boxClass:"wow",animateClass:"animated",offset:0,mobile:!0,live:!0,callback:function(){},scrollContainer:null});i.init();var s=$(".owl-carousel");s.owlCarousel({items:5,loop:!0,margin:0,autoplay:!0,autoplayTimeout:1500,autoplayHoverPause:!0,responsive:{0:{items:1,dots:!1,nav:!1},600:{items:2,dots:!1,nav:!1},960:{items:3,dots:!1,nav:!0},1200:{items:4,dots:!1,nav:!0}}});var s=$(".slider-alar");s.owlCarousel({animateOut:"fadeOut",startDragging:"pauseOnDragging",touchDrag:false,mouseDrag:false,animateIn:"fadeIn",items:1,loop:!0,margin:0,autoplay:!0,lazyLoad:!0,autoplayTimeout:4e3,autoplayHoverPause:!1,smartSpeed:0,responsive:{0:{items:1,dots:!1,nav:!1},600:{items:1,dots:!1,nav:!0}}});var s=$(".test-carrusel");s.owlCarousel({animateOut:"fadeOutDown",animateIn:"fadeIn",items:1,loop:!0,margin:0,autoplay:!0,lazyLoad:!0,autoplayTimeout:3e3,autoplayHoverPause:!1,smartSpeed:450,responsive:{0:{items:1,dots:!1,nav:!1},600:{items:1,dots:!1,nav:!0}}}),$("#ok").hide(),$("#wpcf7-f7-o1").find("form").addClass("fcontact"),$(".fcontact").validate({rules:{nombre:{required:!0,minlength:2},email:{required:!0,email:!0},pais:{required:!0,minlength:2},cmensaje:{required:!0,minlength:2}},messages:{nombre:"Campo invalido",email:"Campo invalido",pais:"Campo invalido",cmensaje:"Campo invalido"},invalidHandler:function(){setTimeout(function(){t()},10)}}),$(".fsuscripcion").find("form").addClass("fsuscrip"),$(".fsuscrip").validate({rules:{nscorreo:{required:!0,email:!0}},messages:{nscorreo:"Campo invalido"},invalidHandler:function(){setTimeout(function(){t()},10)}});for(var n=$(".input--minoru"),r=0;r<n.length;r++)n.eq(r).find(".wpcf7-form-control-wrap").before(n.eq(r).find(".input__field--yoko"));$("#cat-btn").on("click",function(){$(".preg-cat").toggle("slow")}),equalheight=function(t){var e,i=0,s=0,n=[];$(t).each(function(){if(e=$(this),$(e).height("auto"),topPostion=e.position().top,s!=topPostion){for(currentDiv=0;currentDiv<n.length;currentDiv++)n[currentDiv].height(i);n.length=0,s=topPostion,i=e.height(),n.push(e)}else n.push(e),i=i<e.height()?e.height():i;for(currentDiv=0;currentDiv<n.length;currentDiv++)n[currentDiv].height(i)})},$(window).load(function(){equalheight(".clie-carrusel .clie-item"),equalheight(".car-titulo"),equalheight(".preg-preglist"),equalheight(".inscrip-item p"),equalheight(".vacante-list")}),jQuery(window).width()>750&&$(window).load(function(){equalheight(".benef-titulo")}),$(".collapsible").collapsible({accordion:!0}),$(".collapsible2").collapsible({accordion:!0}),$(".select-u").material_select(),$("#contacto-tab").on("click","a",function(){$("#contacto-tab").find("a").removeClass("active-2"),$(this).parent().next().find("a").addClass("active-2")})}),/*!
 * classie - class helper functions
 **/
function(t){"use strict";function e(t){return RegExp("(^|\\s+)"+t+"(\\s+|$)")}function i(t,e){var i=s(t,e)?r:n;i(t,e)}var s,n,r;"classList"in document.documentElement?(s=function(t,e){return t.classList.contains(e)},n=function(t,e){t.classList.add(e)},r=function(t,e){t.classList.remove(e)}):(s=function(t,i){return e(i).test(t.className)},n=function(t,e){s(t,e)||(t.className=t.className+" "+e)},r=function(t,i){t.className=t.className.replace(e(i)," ")});var o={hasClass:s,addClass:n,removeClass:r,toggleClass:i,has:s,add:n,remove:r,toggle:i};"function"==typeof define&&define.amd?define(o):t.classie=o}(window);